name: DeaDBeeF Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 7 1/10 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: artixlinux/artixlinux:latest
    steps:
    - uses: actions/checkout@v4

    - name: Get dependencies
      run: chmod +x ./get-dependencies.sh && ./get-dependencies.sh

    - name: Make AppImage
      run: |
        chmod a+x ./*-appimage.sh && ./*-appimage.sh
        mkdir dist
        mv *.AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeaDBeeF-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4
          with:
            name: DeaDBeeF-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
